import type { ProtocolConfig, FieldDef } from "@/lib/types";

/**
 * Generate a self-contained, *compilable* C pair (`<name>.h` + `<name>.c`) from
 * a protocol definition. The header holds the macros, packed struct, and
 * function prototypes; the source holds the implementations, the head/tail byte
 * tables, and a guarded `main()` demo. Both mirror the app's parser contract so
 * they can be dropped into an MCU / host project:
 *  - a packed frame `struct` whose members follow the field offsets/widths
 *  - endian-aware read/write helpers
 *  - checksum fill (sum / xor / crc8 / crc16-modbus / crc32)
 *  - decode (raw bytes → struct) and encode (struct → wire buffer)
 */
export interface GeneratedCFiles {
  /** Base file name without extension (e.g. "my_protocol"). */
  base: string;
  header: string;
  source: string;
  /** A standalone `main.c` demo that links against the library. */
  main: string;
  /** A `CMakeLists.txt` that builds the demo executable. */
  cmake: string;
}

export function generateCProtocol(cfg: ProtocolConfig): GeneratedCFiles {
  const name = cfg.name || "protocol";
  const ident = sanitizeIdent(name);
  const safeIdent = ident;
  const guard = `${safeIdent.toUpperCase()}_H`;
  const structName = safeIdent;
  const U = structName.toUpperCase();
  const endian = cfg.endian ?? "big";

  // Determine total frame size from the largest field end (head/tail/checksum
  // are appended outside the struct, but we size the struct to hold the fields).
  let maxEnd = 0;
  for (const f of cfg.fields) maxEnd = Math.max(maxEnd, f.offset + f.length);
  const checksumAlgo = cfg.checksum?.algo ?? "none";
  const hasChecksum = checksumAlgo !== "none";
  const checksumLen = checksumDefineLen(checksumAlgo);

  const head = cfg.head ? hexArray(cfg.head as unknown as string | number[]) : [];
  const tail = cfg.tail ? hexArray(cfg.tail as unknown as string | number[]) : [];
  const headBytes = head.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
  const tailBytes = tail.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");

  const members = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => {
      const isStr = f.dataType === "hexstring" || f.dataType === "asciistring";
      const dim = isStr ? `[${Math.max(1, f.length)}]` : "";
      return `    ${cType(f)} ${sanitizeIdent(f.name)}${dim};${fieldComment(f)}`;
    })
    .join("\n");

  // Decode functions write values into the packed struct; encode reads them.
  const decodeLines = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => decodeLine(f, structName, endian))
    .join("\n");
  const encodeLines = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => encodeLine(f, structName, endian))
    .join("\n");

  // Demo: sample literal values per field, formatted for C initialisation.
  const demoInit = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => demoLiteral(f))
    .join("\n    ");
  const demoPrint = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => demoPrintLine(f))
    .join("\n");

  const headLen = head.length > 0 ? `${U}_HEAD_LEN` : "0";
  const tailLen = tail.length > 0 ? `${U}_TAIL_LEN` : "0";

  const header = `/* Auto-generated by DevOps Station — Protocol Designer */
#ifndef ${guard}
#define ${guard}

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Protocol: ${escapeC(name)} */
#define ${U}_ENDIAN_${endian.toUpperCase()}

${hasChecksum ? checksumDefine(checksumAlgo) : "/* no checksum configured */\n"}
/* Frame head / tail / body lengths (hex). */
#define ${U}_HEAD_LEN   ${head.length}
#define ${U}_TAIL_LEN   ${tail.length}
/* Body length is derived from the field layout (max offset + length). */
#define ${U}_BODY_LEN   ${maxEnd}
#define ${U}_FRAME_SIZE  (${U}_HEAD_LEN + ${U}_BODY_LEN${hasChecksum ? " + CHECKSUM_LEN" : ""} + ${U}_TAIL_LEN)
${head.length > 0 ? `extern const uint8_t ${U}_HEAD_BYTES[${head.length}];` : "/* no frame head */"}
${tail.length > 0 ? `extern const uint8_t ${U}_TAIL_BYTES[${tail.length}];` : "/* no frame tail */"}

/* Field count, handy for loops / demos. */
#define ${U}_FIELD_COUNT  ${cfg.fields.length}

#if defined(_MSC_VER)
#pragma pack(push, 1)
#endif
/* The decoded frame. Field order follows the protocol definition. */
typedef struct __attribute__((packed)) {
${members || "    /* no fields defined */"}
} ${structName}_frame_t;
#if defined(_MSC_VER)
#pragma pack(pop)
#endif

/* Fill the last CHECKSUM_LEN bytes of \`buf\` over \`[start, end)\`.
 * Returns 0 on success, -1 if the range is too small for the algorithm. */
int ${structName}_fill_checksum(uint8_t *buf, size_t start, size_t end);

/* Decode raw bytes into a frame struct. Validates head, tail and checksum,
 * then applies endianness. Returns 0 on success, -1 on error. */
int ${structName}_decode(const uint8_t *raw, size_t raw_len, ${structName}_frame_t *out);

/* Encode a frame struct into a wire buffer: head + fields + checksum + tail.
 * Returns the number of bytes written, or 0 on overflow. */
size_t ${structName}_encode(const ${structName}_frame_t *frame, uint8_t *out, size_t out_cap);

#ifdef __cplusplus
}
#endif

#endif /* ${guard} */
`;

  const source = `/* Auto-generated by DevOps Station — Protocol Designer (implementation) */
#include "${structName}.h"

/* Frame head / tail byte tables. */
${head.length > 0 ? `const uint8_t ${U}_HEAD_BYTES[${head.length}] = { ${headBytes} };` : "/* no frame head */"}
${tail.length > 0 ? `const uint8_t ${U}_TAIL_BYTES[${tail.length}] = { ${tailBytes} };` : "/* no frame tail */"}

/* ---------------------------------------------------------------------------
 * Endian helpers — read/write multi-byte fields at an arbitrary byte offset.
 * ------------------------------------------------------------------------- */
${endianHelperFns(endian, structName)}

/* ---------------------------------------------------------------------------
 * Checksum — fills the last CHECKSUM_LEN bytes of \`buf\` over \`[start, end)\`.
 * ------------------------------------------------------------------------- */
int ${structName}_fill_checksum(uint8_t *buf, size_t start, size_t end) {
    if (end < start || (size_t)(end - start) < CHECKSUM_LEN) return -1;
    size_t cs_pos = end - CHECKSUM_LEN;
${checksumFillBody(checksumAlgo, structName)}
    return 0;
}

/* Decode raw bytes into a frame struct. Validates head, tail and checksum,
 * then applies endianness. Returns 0 on success, -1 on error. */
int ${structName}_decode(const uint8_t *raw, size_t raw_len, ${structName}_frame_t *out) {
    if (!raw || !out) return -1;
    const size_t body_off = ${U}_HEAD_LEN;
    const size_t body_len = ${U}_BODY_LEN;
    const size_t need = body_off + body_len${hasChecksum ? " + CHECKSUM_LEN" : ""} + ${U}_TAIL_LEN;
    if (raw_len < need) return -1;
${head.length > 0 ? `    if (memcmp(raw, ${U}_HEAD_BYTES, ${U}_HEAD_LEN) != 0) return -1;  /* frame head */\n` : ""}
${tail.length > 0 ? `    if (memcmp(raw + raw_len - ${U}_TAIL_LEN, ${U}_TAIL_BYTES, ${U}_TAIL_LEN) != 0) return -1;  /* frame tail */\n` : ""}
${hasChecksum ? `    /* Recompute the checksum over [0, body_off+body_len+CHECKSUM_LEN) — the
       same range encode covered — and compare. tmp must include the checksum
       slot so the recompute writes in-bounds. */
    uint8_t crc_buf[CHECKSUM_LEN];
    memcpy(crc_buf, raw + body_off + body_len, CHECKSUM_LEN);
    uint8_t tmp[body_off + body_len + CHECKSUM_LEN];
    memcpy(tmp, raw, body_off + body_len + CHECKSUM_LEN);
    if (${structName}_fill_checksum(tmp, 0, body_off + body_len + CHECKSUM_LEN) != 0) return -1;
    if (memcmp(crc_buf, tmp + body_off + body_len, CHECKSUM_LEN) != 0) return -1;
` : ""}
    const uint8_t *p = raw + body_off;
${decodeLines}
    return 0;
}

/* Encode a frame struct into a wire buffer: head + fields + checksum + tail.
 * Returns the number of bytes written, or 0 on overflow. */
size_t ${structName}_encode(const ${structName}_frame_t *frame, uint8_t *out, size_t out_cap) {
    if (!frame || !out) return 0;
    const size_t needed = ${U}_HEAD_LEN + ${U}_BODY_LEN${hasChecksum ? " + CHECKSUM_LEN" : ""} + ${U}_TAIL_LEN;
    if (out_cap < needed) return 0;  /* check capacity BEFORE touching out */
    size_t n = 0;
${head.length > 0 ? `    memcpy(out + n, ${U}_HEAD_BYTES, ${U}_HEAD_LEN); n += ${U}_HEAD_LEN;\n` : ""}
${encodeLines}
    n += ${U}_BODY_LEN;
${hasChecksum ? `    if (${structName}_fill_checksum(out, 0, n + CHECKSUM_LEN) != 0) return 0;  /* end includes checksum */
    n += CHECKSUM_LEN;
` : ""}
${tail.length > 0 ? `    memcpy(out + n, ${U}_TAIL_BYTES, ${U}_TAIL_LEN); n += ${U}_TAIL_LEN;\n` : ""}
    return n;
}
`;

  // A self-contained `main.c` demo: build a sample frame, encode it, print the
  // hex, decode it back and print the parsed fields. Kept separate from
  // `protocol.c` so the library stays free of a second entry point.
  const mainBody = `int main(void) {
    ${structName}_frame_t f = {
    ${demoInit || "        0" /* placeholder so the struct initialiser is valid */
        }
    };
    uint8_t wire[${U}_FRAME_SIZE];
    size_t len = ${structName}_encode(&f, wire, sizeof(wire));
    if (len == 0) { printf("encode failed\\n"); return 1; }

    printf("${escapeC(name)} demo\\n");
    printf("encoded %zu bytes: ", len);
    for (size_t i = 0; i < len; i++) printf("%02X ", wire[i]);
    printf("\\n");

    ${structName}_frame_t back;
    if (${structName}_decode(wire, len, &back) != 0) { printf("decode failed\\n"); return 1; }
${demoPrint}

    return 0;
}`;

  const mainSource = `/* Auto-generated by DevOps Station — Protocol Designer (demo) */
#include <stdio.h>
#include "${structName}.h"

${mainBody}
`;

  const cmake = `# CMake project for the generated protocol codec.
#   cmake -S . -B build && cmake --build build && ./build/${structName}_demo
cmake_minimum_required(VERSION 3.10)
project(${structName} C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

add_executable(${structName}_demo
    main.c
    ${structName}.c
)

# Pull in the generated header (it lives next to this file).
target_include_directories(${structName}_demo PRIVATE \${CMAKE_CURRENT_SOURCE_DIR})
`;

  return { base: structName, header, source, main: mainSource, cmake };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitizeIdent(s: string): string {
  const cleaned = s.replace(/[^A-Za-z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
  // If nothing survived as a usable identifier (e.g. a CJK-only name that
  // collapsed to underscores), fall back so the generated C stays valid.
  return /[A-Za-z0-9]/.test(cleaned) ? cleaned : "protocol";
}

function escapeC(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\//g, "\\/").replace(/\*/g, "\\*");
}

function cType(f: FieldDef): string {
  switch (f.dataType) {
    case "uint8":
      return "uint8_t";
    case "int16":
      return "int16_t";
    case "uint16":
      return "uint16_t";
    case "int32":
      return "int32_t";
    case "uint32":
      return "uint32_t";
    case "float32":
      return "float";
    case "float64":
      return "double";
    case "hexstring":
    case "asciistring":
      return "uint8_t"; // array dimension is appended after the member name
    case "bitfield":
      return f.length <= 1 ? "uint8_t" : f.length <= 2 ? "uint16_t" : "uint32_t";
    default:
      return "uint8_t";
  }
}

function fieldComment(f: FieldDef): string {
  const parts: string[] = [];
  parts.push(`@${f.offset}`);
  if (f.scale) parts.push(`scale=${f.scale}`);
  if (f.unit) parts.push(`unit=${f.unit}`);
  if (f.enumMap && Object.keys(f.enumMap).length) {
    const m = Object.entries(f.enumMap)
      .map(([k, v]) => `${k}=${v}`)
      .join(",");
    parts.push(`enum{${m}}`);
  }
  if (f.condition) parts.push(`if(${f.condition})`);
  return `  /* ${parts.join(" ")} */`;
}

function checksumDefineLen(algo: string): number {
  if (algo === "crc32") return 4;
  if (algo === "crc16modbus") return 2;
  if (algo === "crc8" || algo === "sum" || algo === "xor") return 1;
  return 0;
}

function checksumDefine(algo: string): string {
  return `#define CHECKSUM_LEN ${checksumDefineLen(algo)}  /* ${algo} */\n`;
}

/** Bytes of a hex string or number[] in canonical form. */
function hexArray(v: string | number[] | null | undefined): number[] {
  if (!v) return [];
  const arr = typeof v === "string" ? v.replace(/[^0-9a-fA-F]/g, "").match(/.{1,2}/g) ?? [] : v;
  return (typeof v === "string" ? arr : (v as number[])).map((b) =>
    typeof b === "string" ? parseInt(b, 16) : b,
  );
}

function endianHelperFns(endian: string, pre: string): string {
  if (endian === "little") {
    return `static uint16_t ${pre}_rd16(const uint8_t *p) { return (uint16_t)(p[0] | (p[1] << 8)); }
static uint32_t ${pre}_rd32(const uint8_t *p) { return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static float    ${pre}_rd_f32(const uint8_t *p) { uint32_t v = ${pre}_rd32(p); float x; memcpy(&x, &v, 4); return x; }
static double   ${pre}_rd_f64(const uint8_t *p) { uint64_t v = 0; for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i); double x; memcpy(&x, &v, 8); return x; }
static void ${pre}_wr16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); }
static void ${pre}_wr32(uint8_t *p, uint32_t v) { for (int i = 0; i < 4; i++) p[i] = (uint8_t)(v >> (8 * i)); }
static void ${pre}_wr_f32(uint8_t *p, float x) { uint32_t v; memcpy(&v, &x, 4); ${pre}_wr32(p, v); }
static void ${pre}_wr_f64(uint8_t *p, double x) { uint64_t v; memcpy(&v, &x, 8); for (int i = 0; i < 8; i++) p[i] = (uint8_t)(v >> (8 * i)); }`;
  }
  return `static uint16_t ${pre}_rd16(const uint8_t *p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint32_t ${pre}_rd32(const uint8_t *p) { return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | p[3]; }
static float    ${pre}_rd_f32(const uint8_t *p) { uint32_t v = ${pre}_rd32(p); float x; memcpy(&x, &v, 4); return x; }
static double   ${pre}_rd_f64(const uint8_t *p) { uint64_t v = 0; for (int i = 0; i < 8; i++) v = (v << 8) | p[i]; double x; memcpy(&x, &v, 8); return x; }
static void ${pre}_wr16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)(v >> 8); p[1] = (uint8_t)v; }
static void ${pre}_wr32(uint8_t *p, uint32_t v) { for (int i = 3; i >= 0; i--) p[i] = (uint8_t)(v >> (8 * (3 - i))); }
static void ${pre}_wr_f32(uint8_t *p, float x) { uint32_t v; memcpy(&v, &x, 4); ${pre}_wr32(p, v); }
static void ${pre}_wr_f64(uint8_t *p, double x) { uint64_t v; memcpy(&v, &x, 8); for (int i = 7; i >= 0; i--) p[i] = (uint8_t)(v >> (8 * (7 - i))); }`;
}

function checksumFillBody(algo: string, pre: string): string {
  switch (algo) {
    case "sum":
      return `    uint8_t s = 0;
    for (size_t i = start; i < cs_pos; i++) s = (uint8_t)(s + buf[i]);
    buf[cs_pos] = s;`;
    case "xor":
      return `    uint8_t x = 0;
    for (size_t i = start; i < cs_pos; i++) x ^= buf[i];
    buf[cs_pos] = x;`;
    case "crc8":
      return `    uint8_t crc = 0x00;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x80) ? (uint8_t)((crc << 1) ^ 0x07) : (uint8_t)(crc << 1);
    }
    buf[cs_pos] = crc;`;
    case "crc16modbus":
      return `    uint16_t crc = 0xFFFF;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x0001) ? (uint16_t)((crc >> 1) ^ 0xA001) : (uint16_t)(crc >> 1);
    }
    ${pre}_wr16(buf + cs_pos, crc);`;
    case "crc32":
      return `    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x00000001u) ? (crc >> 1) ^ 0xEDB88320u : crc >> 1;
    }
    crc = ~crc;
    ${pre}_wr32(buf + cs_pos, crc);`;
    default:
      return `    /* no checksum: nothing to fill */`;
  }
}

/** One decode line writing raw bytes at the field offset into the struct. */
function decodeLine(f: FieldDef, structName: string, endian: string): string {
  const id = sanitizeIdent(f.name);
  const off = f.offset;
  switch (f.dataType) {
    case "uint8":
    case "bitfield": // bitfields <= 4 bytes map to an unsigned int
      return `    out->${id} = p[${off}];`;
    case "int16":
      return `    out->${id} = (int16_t)${structName}_rd16(p + ${off});`;
    case "uint16":
      return `    out->${id} = ${structName}_rd16(p + ${off});`;
    case "int32":
    case "uint32":
      return `    out->${id} = ${structName}_rd32(p + ${off});`;
    case "float32":
      return `    out->${id} = ${structName}_rd_f32(p + ${off});`;
    case "float64":
      return `    out->${id} = ${structName}_rd_f64(p + ${off});`;
    case "hexstring":
    case "asciistring":
      return `    memcpy(out->${id}, p + ${off}, ${Math.max(1, f.length)});`;
    default:
      return `    out->${id} = p[${off}];`;
  }
}

/** One encode line writing the struct field into the wire buffer at offset `n`. */
function encodeLine(f: FieldDef, structName: string, endian: string): string {
  const id = sanitizeIdent(f.name);
  const off = f.offset;
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
      return `    out[n + ${off}] = (uint8_t)frame->${id};`;
    case "int16":
    case "uint16":
      return `    { uint16_t v = (uint16_t)frame->${id}; ${structName}_wr16(out + n + ${off}, v); }`;
    case "int32":
    case "uint32":
      return `    { uint32_t v = (uint32_t)frame->${id}; ${structName}_wr32(out + n + ${off}, v); }`;
    case "float32":
      return `    ${structName}_wr_f32(out + n + ${off}, frame->${id});`;
    case "float64":
      return `    ${structName}_wr_f64(out + n + ${off}, frame->${id});`;
    case "hexstring":
    case "asciistring":
      return `    memcpy(out + n + ${off}, frame->${id}, ${Math.max(1, f.length)});`;
    default:
      return `    out[n + ${off}] = (uint8_t)frame->${id};`;
  }
}

/** A C struct initialiser value for the demo. */
function demoLiteral(f: FieldDef): string {
  const id = sanitizeIdent(f.name);
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
      return `.${id} = 0x${sampleInt(f, 0xff).toString(16)},`;
    case "int16":
    case "int32":
      return `.${id} = ${sampleInt(f, 1024) - 512},`;
    case "uint16":
    case "uint32":
      return `.${id} = ${sampleInt(f, 1024)},`;
    case "float32":
      return `.${id} = 1.5f,`;
    case "float64":
      return `.${id} = 2.25,`;
    case "hexstring":
    case "asciistring": {
      const len = Math.max(1, f.length);
      const bytes = Array.from({ length: len }, (_, i) =>
        `0x${(0x41 + (i % 26)).toString(16).padStart(2, "0")}`,
      ).join(", ");
      return `.${id} = { ${bytes} },`;
    }
    default:
      return `.${id} = 0,`;
  }
}

/** A printf line in the demo that shows the decoded value back. */
function demoPrintLine(f: FieldDef): string {
  const id = sanitizeIdent(f.name);
  if (f.dataType === "hexstring" || f.dataType === "asciistring") {
    return `    printf("  ${id} (string): ");
    for (size_t i = 0; i < ${Math.max(1, f.length)}; i++) printf("%02X ", back.${id}[i]);
    printf("\\n");`;
  }
  const unit = f.unit ? ` (${escapeC(f.unit)})` : "";
  // When a scale is configured the real value is `raw / scale`, which is a
  // double — print it with %g (never %d, which is undefined behaviour with a
  // floating-point argument).
  if (f.scale) {
    return `    printf("  ${id} = %g${unit}\\n", (double)back.${id} / ${f.scale});`;
  }
  let spec = "%d";
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
    case "uint16":
    case "uint32":
      spec = "%u";
      break;
    case "int16":
    case "int32":
      spec = "%d";
      break;
    case "float32":
    case "float64":
      spec = "%g";
      break;
  }
  return `    printf("  ${id} = ${spec}${unit}\\n", back.${id});`;
}

/** Pick a stable sample integer derived from the field, clamped to `max`. */
function sampleInt(f: FieldDef, max: number): number {
  let h = 0;
  for (let i = 0; i < f.name.length; i++) h = (h * 31 + f.name.charCodeAt(i)) & 0xffff;
  return 1 + (h % Math.max(1, max - 1));
}
