import type { ProtocolConfig, FieldDef } from "@/lib/types";

/**
 * Generate a self-contained, *compilable* C source file (`<name>.h` + inline
 * helpers + a demo `main`) from a protocol definition. The output mirrors the
 * app's parser contract and ships with working implementations so it can be
 * dropped straight into an MCU / host project and built:
 *  - a packed frame `struct` whose members follow the field offsets/widths
 *  - endian-aware read/write helpers
 *  - checksum fill (sum / xor / crc8 / crc16-modbus / crc32)
 *  - decode (raw bytes → struct) and encode (struct → wire buffer)
 *  - a `main()` that builds a sample frame, fills the checksum, prints it,
 *    then decodes it back and prints the parsed fields.
 */
export function generateCProtocol(cfg: ProtocolConfig): string {
  const name = cfg.name || "protocol";
  const ident = sanitizeIdent(name);
  const hasLetter = /[A-Za-z]/.test(name);
  const safeIdent = hasLetter ? ident : "protocol";
  const guard = hasLetter ? `PROTOCOL_${ident.toUpperCase()}_H` : "PROTOCOL_H";
  const structName = safeIdent || "protocol";
  const U = structName.toUpperCase();
  const endian = cfg.endian ?? "big";

  // Determine total frame size from the largest field end (head/tail/checksum
  // are appended outside the struct, but we size the struct to hold the fields).
  let maxEnd = 0;
  for (const f of cfg.fields) maxEnd = Math.max(maxEnd, f.offset + f.length);
  const checksumAlgo = cfg.checksum?.algo ?? "none";
  const hasChecksum = checksumAlgo !== "none";
  const checksumLen = checksumDefineLen(checksumAlgo);

  const head = cfg.head ? hexArray(cfg.head as unknown as string | number[]) : [];
  const tail = cfg.tail ? hexArray(cfg.tail as unknown as string | number[]) : [];
  const headBytes = head.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");
  const tailBytes = tail.map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ");

  const members = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => `    ${cType(f)} ${sanitizeIdent(f.name)};${fieldComment(f)}`)
    .join("\n");

  // Decode functions write values into the packed struct; encode reads them.
  const decodeLines = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => decodeLine(f, U, endian))
    .join("\n");
  const encodeLines = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => encodeLine(f, U, endian))
    .join("\n");

  // Demo: sample literal values per field, formatted for C initialisation.
  const demoInit = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => demoLiteral(f))
    .join("\n    ");
  const demoPrint = cfg.fields
    .slice()
    .sort((a, b) => a.offset - b.offset)
    .map((f) => demoPrintLine(f))
    .join("\n");

  const headConst =
    head.length > 0
      ? `static const uint8_t ${U}_HEAD_BYTES[${head.length}] = { ${headBytes} };\n`
      : "";
  const tailConst =
    tail.length > 0
      ? `static const uint8_t ${U}_TAIL_BYTES[${tail.length}] = { ${tailBytes} };\n`
      : "";

  const body = `/* Auto-generated by DevOps Station — Protocol Designer */
#ifndef ${guard}
#define ${guard}

#include <stdint.h>
#include <string.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Protocol: ${escapeC(name)} */
#define ${U}_FRAME_SIZE  (${maxEnd}${hasChecksum ? " + CHECKSUM_LEN" : ""})
#define ${U}_ENDIAN_${endian.toUpperCase()}

${hasChecksum ? checksumDefine(checksumAlgo) : "/* no checksum configured */\n"}
/* Frame head / tail (hex). */
${head.length > 0 ? `#define ${U}_HEAD_LEN   ${head.length}` : `/* no frame head */`}
${tail.length > 0 ? `#define ${U}_TAIL_LEN   ${tail.length}` : `/* no frame tail */`}
${headConst}${tailConst}
/* Field count, handy for loops / demos. */
#define ${U}_FIELD_COUNT  ${cfg.fields.length}

/* The decoded frame. Field order follows the protocol definition. */
typedef struct __attribute__((packed)) {
${members || "    /* no fields defined */"}
} ${structName}_frame_t;

/* ---------------------------------------------------------------------------
 * Endian helpers — read/write multi-byte fields at an arbitrary byte offset.
 * Generated code is endian-agnostic via these, matching the app's endian.
 * ------------------------------------------------------------------------- */
${endianHelperFns(endian)}

/* ---------------------------------------------------------------------------
 * Checksum — fills the last CHECKSUM_LEN bytes of \`buf\` over \`[start, end)\`.
 * Returns 0 on success, -1 if the range is too small for the algorithm.
 * ------------------------------------------------------------------------- */
int ${structName}_fill_checksum(uint8_t *buf, size_t start, size_t end) {
    if (end < start || (size_t)(end - start) < CHECKSUM_LEN) return -1;
    size_t cs_pos = end - CHECKSUM_LEN;
${checksumFillBody(checksumAlgo, U)}
    return 0;
}

/* Decode raw bytes into a frame struct. Skips frame head, applies endianness.
 * Returns 0 on success, -1 on error (buffer too small). */
int ${structName}_decode(const uint8_t *raw, size_t raw_len, ${structName}_frame_t *out) {
    if (!raw || !out) return -1;
    size_t body_off = ${head.length > 0 ? `${U}_HEAD_LEN` : "0"};
    size_t body_len = ${maxEnd};
    if (raw_len < body_off + body_len${hasChecksum ? " + CHECKSUM_LEN" : ""}) return -1;
    const uint8_t *p = raw + body_off;
${decodeLines}
    return 0;
}

/* Encode a frame struct into a wire buffer: head + fields + checksum + tail.
 * Returns the number of bytes written, or 0 on overflow. */
size_t ${structName}_encode(const ${structName}_frame_t *frame, uint8_t *out, size_t out_cap) {
    if (!frame || !out) return 0;
    size_t n = 0;
${head.length > 0 ? `    memcpy(out + n, ${U}_HEAD_BYTES, ${U}_HEAD_LEN); n += ${U}_HEAD_LEN;\n` : ""}
${encodeLines}
${hasChecksum ? `    if (${structName}_fill_checksum(out, 0, n) != 0) return 0;\n` : ""}
${tail.length > 0 ? `    if (n + ${U}_TAIL_LEN > out_cap) return 0;\n    memcpy(out + n, ${U}_TAIL_BYTES, ${U}_TAIL_LEN); n += ${U}_TAIL_LEN;\n` : ""}
    return n;
}

/* ---------------------------------------------------------------------------
 * DEMO — build a sample frame, encode it, print it, decode it back, and print
 * the parsed fields. Compile this file standalone (with -D${U}_DEMO_MAIN) to
 * run it, e.g.:  cc ${sanitizeIdent(name)}.h -D${U}_DEMO_MAIN -o demo && ./demo
 * ------------------------------------------------------------------------- */
#ifdef ${U}_DEMO_MAIN
int main(void) {
    ${structName}_frame_t f = {
    ${demoInit || "        0" /* placeholder so the struct initialiser is valid */
        }
    };
    uint8_t wire[${U}_FRAME_SIZE + ${head.length > 0 ? `${U}_HEAD_LEN` : "0"} + ${tail.length > 0 ? `${U}_TAIL_LEN` : "0"}];
    size_t len = ${structName}_encode(&f, wire, sizeof(wire));
    if (len == 0) { printf("encode failed\\n"); return 1; }

    printf("${escapeC(name)} demo\\n");
    printf("encoded %zu bytes: ", len);
    for (size_t i = 0; i < len; i++) printf("%02X ", wire[i]);
    printf("\\n");

    ${structName}_frame_t back;
    if (${structName}_decode(wire, len, &back) != 0) { printf("decode failed\\n"); return 1; }
${demoPrint}

    return 0;
}
#endif /* ${U}_DEMO_MAIN */

#ifdef __cplusplus
}
#endif

#endif /* ${guard} */
`;

  return body;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sanitizeIdent(s: string): string {
  const cleaned = s.replace(/[^A-Za-z0-9_]/g, "_").replace(/^([0-9])/, "_$1");
  // If nothing survived as a usable identifier (e.g. a CJK-only name that
  // collapsed to underscores), fall back so the generated C stays valid.
  return /[A-Za-z0-9]/.test(cleaned) ? cleaned : "field";
}

function escapeC(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/\//g, "\\/").replace(/\*/g, "\\*");
}

function cType(f: FieldDef): string {
  switch (f.dataType) {
    case "uint8":
      return "uint8_t";
    case "int16":
      return "int16_t";
    case "uint16":
      return "uint16_t";
    case "int32":
      return "int32_t";
    case "uint32":
      return "uint32_t";
    case "float32":
      return "float";
    case "float64":
      return "double";
    case "hexstring":
    case "asciistring":
      return `uint8_t[${Math.max(1, f.length)}]`;
    case "bitfield":
      return f.length <= 1 ? "uint8_t" : f.length <= 2 ? "uint16_t" : "uint32_t";
    default:
      return "uint8_t";
  }
}

function fieldComment(f: FieldDef): string {
  const parts: string[] = [];
  parts.push(`@${f.offset}`);
  if (f.scale) parts.push(`scale=${f.scale}`);
  if (f.unit) parts.push(`unit=${f.unit}`);
  if (f.enumMap && Object.keys(f.enumMap).length) {
    const m = Object.entries(f.enumMap)
      .map(([k, v]) => `${k}=${v}`)
      .join(",");
    parts.push(`enum{${m}}`);
  }
  if (f.condition) parts.push(`if(${f.condition})`);
  return `  /* ${parts.join(" ")} */`;
}

function checksumDefineLen(algo: string): number {
  if (algo === "crc32") return 4;
  if (algo === "crc16modbus") return 2;
  if (algo === "crc8" || algo === "sum" || algo === "xor") return 1;
  return 0;
}

function checksumDefine(algo: string): string {
  return `#define CHECKSUM_LEN ${checksumDefineLen(algo)}  /* ${algo} */\n`;
}

/** Bytes of a hex string or number[] in canonical form. */
function hexArray(v: string | number[] | null | undefined): number[] {
  if (!v) return [];
  const arr = typeof v === "string" ? v.replace(/[^0-9a-fA-F]/g, "").match(/.{1,2}/g) ?? [] : v;
  return (typeof v === "string" ? arr : (v as number[])).map((b) =>
    typeof b === "string" ? parseInt(b, 16) : b,
  );
}

function endianHelperFns(endian: string): string {
  if (endian === "little") {
    return `static uint16_t rd16(const uint8_t *p) { return (uint16_t)(p[0] | (p[1] << 8)); }
static uint32_t rd32(const uint8_t *p) { return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24); }
static float    rd_f32(const uint8_t *p) { uint32_t v = rd32(p); float x; memcpy(&x, &v, 4); return x; }
static double   rd_f64(const uint8_t *p) { uint64_t v = 0; for (int i = 0; i < 8; i++) v |= (uint64_t)p[i] << (8 * i); double x; memcpy(&x, &v, 8); return x; }
static void wr16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8); }
static void wr32(uint8_t *p, uint32_t v) { for (int i = 0; i < 4; i++) p[i] = (uint8_t)(v >> (8 * i)); }
static void wr_f32(uint8_t *p, float x) { uint32_t v; memcpy(&v, &x, 4); wr32(p, v); }
static void wr_f64(uint8_t *p, double x) { uint64_t v; memcpy(&v, &x, 8); for (int i = 0; i < 8; i++) p[i] = (uint8_t)(v >> (8 * i)); }`;
  }
  return `static uint16_t rd16(const uint8_t *p) { return (uint16_t)((p[0] << 8) | p[1]); }
static uint32_t rd32(const uint8_t *p) { return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | p[3]; }
static float    rd_f32(const uint8_t *p) { uint32_t v = rd32(p); float x; memcpy(&x, &v, 4); return x; }
static double   rd_f64(const uint8_t *p) { uint64_t v = 0; for (int i = 7; i >= 0; i--) v = (v << 8) | p[i]; double x; memcpy(&x, &v, 8); return x; }
static void wr16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)(v >> 8); p[1] = (uint8_t)v; }
static void wr32(uint8_t *p, uint32_t v) { for (int i = 3; i >= 0; i--) p[i] = (uint8_t)(v >> (8 * (3 - i))); }
static void wr_f32(uint8_t *p, float x) { uint32_t v; memcpy(&v, &x, 4); wr32(p, v); }
static void wr_f64(uint8_t *p, double x) { uint64_t v; memcpy(&v, &x, 8); for (int i = 7; i >= 0; i--) p[i] = (uint8_t)(v >> (8 * (7 - i))); }`;
}

function checksumFillBody(algo: string, _U: string): string {
  switch (algo) {
    case "sum":
      return `    uint8_t s = 0;
    for (size_t i = start; i < cs_pos; i++) s = (uint8_t)(s + buf[i]);
    buf[cs_pos] = s;`;
    case "xor":
      return `    uint8_t x = 0;
    for (size_t i = start; i < cs_pos; i++) x ^= buf[i];
    buf[cs_pos] = x;`;
    case "crc8":
      return `    uint8_t crc = 0x00;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x80) ? (uint8_t)((crc << 1) ^ 0x07) : (uint8_t)(crc << 1);
    }
    buf[cs_pos] = crc;`;
    case "crc16modbus":
      return `    uint16_t crc = 0xFFFF;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x0001) ? (uint16_t)((crc >> 1) ^ 0xA001) : (uint16_t)(crc >> 1);
    }
    wr16(buf + cs_pos, crc);`;
    case "crc32":
      return `    uint32_t crc = 0xFFFFFFFFu;
    for (size_t i = start; i < cs_pos; i++) {
        crc ^= buf[i];
        for (int k = 0; k < 8; k++)
            crc = (crc & 0x00000001u) ? (crc >> 1) ^ 0xEDB88320u : crc >> 1;
    }
    crc = ~crc;
    wr32(buf + cs_pos, crc);`;
    default:
      return `    /* no checksum: nothing to fill */`;
  }
}

/** One decode line writing raw bytes at the field offset into the struct. */
function decodeLine(f: FieldDef, U: string, endian: string): string {
  const id = sanitizeIdent(f.name);
  const off = f.offset;
  switch (f.dataType) {
    case "uint8":
    case "bitfield": // bitfields <= 4 bytes map to an unsigned int
      return `    out->${id} = p[${off}];`;
    case "int16":
      return `    out->${id} = (int16_t)rd16(p + ${off});`;
    case "uint16":
      return `    out->${id} = rd16(p + ${off});`;
    case "int32":
    case "uint32":
      return `    out->${id} = ${endian === "little" ? "rd32" : "rd32"}(p + ${off});`;
    case "float32":
      return `    out->${id} = rd_f32(p + ${off});`;
    case "float64":
      return `    out->${id} = rd_f64(p + ${off});`;
    case "hexstring":
    case "asciistring":
      return `    memcpy(out->${id}, p + ${off}, ${Math.max(1, f.length)});`;
    default:
      return `    out->${id} = p[${off}];`;
  }
}

/** One encode line writing the struct field into the wire buffer at offset `n`. */
function encodeLine(f: FieldDef, U: string, endian: string): string {
  const id = sanitizeIdent(f.name);
  const off = f.offset;
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
      return `    out[n + ${off}] = (uint8_t)frame->${id};`;
    case "int16":
    case "uint16":
      return `    { uint16_t v = (uint16_t)frame->${id}; wr16(out + n + ${off}, v); }`;
    case "int32":
    case "uint32":
      return `    { uint32_t v = (uint32_t)frame->${id}; wr32(out + n + ${off}, v); }`;
    case "float32":
      return `    wr_f32(out + n + ${off}, frame->${id});`;
    case "float64":
      return `    wr_f64(out + n + ${off}, frame->${id});`;
    case "hexstring":
    case "asciistring":
      return `    memcpy(out + n + ${off}, frame->${id}, ${Math.max(1, f.length)});`;
    default:
      return `    out[n + ${off}] = (uint8_t)frame->${id};`;
  }
}

/** A C struct initialiser value for the demo. */
function demoLiteral(f: FieldDef): string {
  const id = sanitizeIdent(f.name);
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
      return `.${id} = 0x${sampleInt(f, 0xff).toString(16)},`;
    case "int16":
    case "int32":
      return `.${id} = ${sampleInt(f, 1024) - 512},`;
    case "uint16":
    case "uint32":
      return `.${id} = ${sampleInt(f, 1024)},`;
    case "float32":
      return `.${id} = 1.5f,`;
    case "float64":
      return `.${id} = 2.25,`;
    case "hexstring":
    case "asciistring": {
      const len = Math.max(1, f.length);
      const bytes = Array.from({ length: len }, (_, i) =>
        `0x${(0x41 + (i % 26)).toString(16).padStart(2, "0")}`,
      ).join(", ");
      return `.${id} = { ${bytes} },`;
    }
    default:
      return `.${id} = 0,`;
  }
}

/** A printf line in the demo that shows the decoded value back. */
function demoPrintLine(f: FieldDef): string {
  const id = sanitizeIdent(f.name);
  let spec = "%d";
  switch (f.dataType) {
    case "uint8":
    case "bitfield":
    case "uint16":
    case "uint32":
      spec = "%u";
      break;
    case "int16":
    case "int32":
      spec = "%d";
      break;
    case "float32":
    case "float64":
      spec = "%g";
      break;
    case "hexstring":
    case "asciistring":
      return `    printf("  ${id} (string): ");
    for (size_t i = 0; i < ${Math.max(1, f.length)}; i++) printf("%02X ", back.${id}[i]);
    printf("\\n");`;
  }
  const unit = f.unit ? ` (${escapeC(f.unit)})` : "";
  const scaled = f.scale ? ` * ${f.scale}` : "";
  return `    printf("  ${id} = ${spec}${unit}\\n", back.${id}${scaled});`;
}

/** Pick a stable sample integer derived from the field, clamped to `max`. */
function sampleInt(f: FieldDef, max: number): number {
  let h = 0;
  for (let i = 0; i < f.name.length; i++) h = (h * 31 + f.name.charCodeAt(i)) & 0xffff;
  return 1 + (h % Math.max(1, max - 1));
}
